### ISSUE TITLE
The pygoocanvas is not installed, try to install it.

### ISSUE THREAD

**Issue by cseas** [nsnam/ns-3-dev-git#35] opened 2018-11-10 03:43 UTC
When trying to install ns-3.29 in Ubuntu LTS 18.04, running `bake.py show` displays the following error:
```
> pygoocanvas - Missing
   >> The pygoocanvas is not installed, try to install it.
   >> Try: "sudo apt-get install python-pygoocanvas", if you have sudo rights.
```
However, this is not the correct solution.
According to the [installation page](https://www.nsnam.org/wiki/Installation#Ubuntu.2FDebian.2FMint):
```
For Ubuntu 18.04, python-pygoocanvas is no longer provided. The ns-3.29 release and later upgrades the support to GTK+ version 3, and requires these packages:

apt-get install gir1.2-goocanvas-2.0 python-gi python-gi-cairo python-pygraphviz python3-gi python3-gi-cairo python3-pygraphviz gir1.2-gtk-3.0 ipython ipython3  

```

Please update bake.py to reflect this.

**Comment by tomhenderson** [comment] 2018-11-10 19:56
I will move this to the ns-3 bug tracker if I can reproduce it.

However, I ask the reporter to please provide more details, because I can't reproduce on an Ubuntu-18.04 machine.

I tried:
```
  wget https://www.nsnam.org/releases/ns-allinone-3.29.tar.bz2
  tar xjf ns-allinone-3.29.tar.bz2
  cd ns-allinone-3.29/bake
  ./bake.py configure -e ns-3.29
  ./bake.py show
```
/* No mention of pygoocanvas, only libgoocanvas2 */

```
  rm -rf bakefile.xml
  ./bake.py configure -e ns-allinone-3.29
  ./bake.py show
```

/* No mention of pygoocanvas, only libgoocanvas2 */

If you get different output, can you attach your bakefile.xml and the result of running the show command?

**Comment by avik111191** [comment] 2019-03-03 17:14
$ bake.py show
 on ubuntu 16.04 LTS showin the same error  Even when both pygoocanvas and cxxfilt is installed

-- System Dependencies --
 > clang-dev - OK
 > cmake - OK
 > cxxfilt - Missing
   >> The python cxxfilt package is not installed, try to install it using 'pip install cxxfilt'.
 > g++ - OK
 > llvm-dev - OK
 > pygoocanvas - Missing
   >> The pygoocanvas is not installed, try to install it.
   >> Try: "sudo apt-get install python-pygoocanvas", if you have sudo rights.
 > pygraphviz - OK
 > python-dev - OK
 > qt4 - OK
 > setuptools - OK

**Comment by tomhenderson** [comment] 2019-03-03 17:34
Hello, I cannot reproduce this.
Can you please try the steps I listed above in a temporary directory, and let me know whether it works or not?

Below I will list the commands to try again, and I will list the output that I get on Ubuntu 16.04:

```
$ wget https://www.nsnam.org/releases/ns-allinone-3.29.tar.bz2
$ tar xjf ns-allinone-3.29.tar.bz2
$ cd ns-allinone-3.29/bake
$ ./bake.py configure -e ns-allinone-3.29
$ ./bake.py show
```


```
-- System Dependencies --
 > automake - OK
 > clang-dev - OK
 > cmake - OK
 > cxxfilt - OK
 > g++ - OK
 > gi-cairo - OK
 > libgoocanvas2 - OK
 > libxml2-dev - OK
 > llvm-dev - OK
 > pygobject - OK
 > pygraphviz - OK
 > python-dev - OK
 > qt - OK
 > setuptools - OK
```

**Comment by tomhenderson** [comment] 2019-09-06 03:09
I am closing this (as we are not taking issues on GitHub.com); if you wish to reopen, please use GitLab.com or our ns-3-users@googlegroups.com forum.

**Closed by tomhenderson** 2019-09-06 03:09 UTC
